services:
  mysql:
    container_name: books_mysql
    environment:
      MYSQL_DATABASE: attractions_db
      MYSQL_PASSWORD: attractions_pass
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: attractions_user
      TZ: Asia/Bangkok
    image: mysql:8.0
    networks:
      stack: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3306
        published: "3307"  # Change the published port to 3307
    restart: unless-stopped
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
        volume: {}
      - type: bind
        source: /var/lib/jenkins/workspace/Final_dit312/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
        bind:
          create_host_path: true
